# Generated by Django 5.2 on 2025-04-13 07:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_appointments"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HealthMetrics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("age", models.CharField(max_length=50)),
                ("systolic_bp", models.CharField(max_length=50)),
                ("diastolic_bp", models.CharField(max_length=50)),
                ("bs", models.CharField(max_length=50)),
                ("body_temp", models.CharField(max_length=50)),
                ("heartrate", models.CharField(max_length=50)),
                ("predicted_risk", models.CharField(max_length=50)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
