# Generated by Django 5.2 on 2025-04-13 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_healthmetrics"),
    ]

    operations = [
        migrations.AddField(
            model_name="healthmetrics",
            name="date",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
