# Generated by Django 5.2 on 2025-04-14 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_healthmetrics_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appointments",
            name="type",
            field=models.CharField(max_length=250),
        ),
    ]
