# Generated by Django 5.2 on 2025-04-28 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0007_profile_provider"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="phone_number",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
