# Generated by Django 5.2 on 2025-04-29 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0009_medicalhistory"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="blood_type",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="due_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
