# Generated by Django 5.2 on 2025-04-29 11:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0012_reports_provider_alter_reports_user"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="reports",
            name="user",
        ),
        migrations.AlterField(
            model_name="reports",
            name="patient",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="received_report",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
