# Generated by Django 5.2 on 2025-04-29 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0013_remove_reports_user_alter_reports_patient"),
    ]

    operations = [
        migrations.AddField(
            model_name="reports",
            name="created_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
