# Generated by Django 5.2 on 2025-04-29 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0015_appointments_provider"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointments",
            name="status",
            field=models.CharField(
                choices=[
                    ("Scheduled", "Scheduled"),
                    ("Completed", "Completed"),
                    ("Cancelled", "Cancelled"),
                    ("Rescheduled", "Rescheduled"),
                ],
                default="Scheduled",
                max_length=20,
            ),
        ),
    ]
