# Generated by Django 5.2 on 2025-04-29 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0016_appointments_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="appointments",
            name="date",
        ),
        migrations.AddField(
            model_name="appointments",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="appointments",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name="appointments",
            name="time",
            field=models.DateTimeField(),
        ),
    ]
