# Generated by Django 5.2 on 2025-04-29 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0017_remove_appointments_date_appointments_created_at_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="appointments",
            old_name="user",
            new_name="patient",
        ),
    ]
