# Generated by Django 5.2 on 2025-04-30 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0018_rename_user_appointments_patient"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="date_joined",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
