# Generated by Django 5.2 on 2025-05-02 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0019_profile_date_joined"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="notifications",
            name="provider",
        ),
        migrations.AddField(
            model_name="notifications",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="notifications",
            name="type",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
