# Generated by Django 5.2 on 2025-05-02 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0020_remove_notifications_provider_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="notifications",
            name="read",
            field=models.CharField(default=False, max_length=50),
        ),
    ]
