# Generated by Django 5.2 on 2025-05-02 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0021_notifications_read"),
    ]

    operations = [
        migrations.AddField(
            model_name="notifications",
            name="details",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
